### ISSUE TITLE
Can the image path contain spaces?

### ISSUE THREAD

**Issue by jamesking** [robwierzbowski/jekyll-picture-tag#59]
Hello,

I have picture tag working well, but it seems to throw an error if the path to the image contains spaces. Is there any way around this?

Here is the liquid tag I am using:

`{% picture thumb {{file.path}} %}`

When `file.path` is  `path/to/file.jpg` it works. When is it `path to file.jpg` i get the following error:

```
Liquid Exception: undefined method `[]' for nil:NilClass in .site/layouts/index.html
<PATH REDACTED>/.site/plugins/picture_tag.rb:43:in `render': undefined method `[]' for nil:NilClass (NoMethodError)
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/liquid-2.6.2/lib/liquid/block.rb:109:in `block in render_all'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `each'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `render_all'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/liquid-2.6.2/lib/liquid/tags/if.rb:40:in `block (2 levels) in render'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/liquid-2.6.2/lib/liquid/tags/if.rb:38:in `each'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/liquid-2.6.2/lib/liquid/tags/if.rb:38:in `block in render'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/liquid-2.6.2/lib/liquid/context.rb:112:in `stack'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/liquid-2.6.2/lib/liquid/tags/if.rb:37:in `render'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/liquid-2.6.2/lib/liquid/block.rb:109:in `block in render_all'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `each'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `render_all'
    from /Users/jamesking/Documents/SP+EE/Projects/DIU-citizen-science-platform/3. Deliverables/.site/plugins/directory_tag.rb:94:in `block (2 levels) in render'
    from /Users/jamesking/Documents/SP+EE/Projects/DIU-citizen-science-platform/3. Deliverables/.site/plugins/directory_tag.rb:62:in `each'
    from /Users/jamesking/Documents/SP+EE/Projects/DIU-citizen-science-platform/3. Deliverables/.site/plugins/directory_tag.rb:62:in `each_with_index'
    from /Users/jamesking/Documents/SP+EE/Projects/DIU-citizen-science-platform/3. Deliverables/.site/plugins/directory_tag.rb:62:in `block in render'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/liquid-2.6.2/lib/liquid/context.rb:112:in `stack'
    from /Users/jamesking/Documents/SP+EE/Projects/DIU-citizen-science-platform/3. Deliverables/.site/plugins/directory_tag.rb:61:in `render'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/liquid-2.6.2/lib/liquid/block.rb:109:in `block in render_all'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `each'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `render_all'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/liquid-2.6.2/lib/liquid/block.rb:82:in `render'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/liquid-2.6.2/lib/liquid/template.rb:128:in `render'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/liquid-2.6.2/lib/liquid/template.rb:138:in `render!'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:106:in `render_liquid'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:205:in `render_all_layouts'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:239:in `do_layout'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/jekyll-2.5.3/lib/jekyll/page.rb:122:in `render'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/jekyll-2.5.3/lib/jekyll/site.rb:298:in `block in render'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `each'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `render'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in `process'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/bin/jekyll:23:in `load'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/bin/jekyll:23:in `<main>'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
    from /Users/jamesking/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
```

Not sure if this is a bug or me doing something silly.

Thanks,
- James

**Comment by jamesking** [comment]
So I have forked jekyll-picture-tag and done a little hacking to make this work for me. I am not sure this is worthy of a pull-request, but these changes allow for images paths with spaces in them but require that the `image_src` be wrapped in double quotes `"…"` 

https://github.com/robwierzbowski/jekyll-picture-tag/compare/master...jamesking:master

**Comment by jamesking** [comment]
I'm don;t think this is worthy of a pull request, but I have experimented with the regex in this fork. 

https://github.com/jamesking/jekyll-picture-tag/commit/39a9bba8045c9219a87e40f862471361c3eac740

As I wrote in the commit message - this causes problems when serving the generated images.

**Comment by btobolaski** [comment]
Does it require all paths to be wrapped in quotes or just the ones with spaces?

**Comment by jamesking** [comment]
Yes - all paths require quotes with these changes.
